# Generated by Django 3.2.7 on 2021-09-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='sobrename',
            new_name='sobrenome',
        ),
    ]
